config/routes.rb
Rails.application.routes.draw do
  get 'landing/index'

root controller: :landing, action: :index
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles do
    resources :comments
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  has_many :comments

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :article

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(safe_param)
    @comment.save
    redirect_to article_path(@article)
  end






  def safe_param
    params.permit(:message, :email)
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @articles = Article.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/show.html.erb
<div>
  <%= @article.title %>
</div>

<div>
<%= @article.content %>
</div>
<div>
by <%= @article.author %>
</div>

<% @article.comments.each do |comment| %>
      <%= comment.message %>
      Posted by: <%= comment.email %>
<% end %>

<%= form_tag article_comments_path(@article.id) do %>
   <div>
     <%= label_tag :message %><br>
     <%= text_area_tag :message %>
   </div>

   <div>
     <%= label_tag :email %><br>
     <%= email_field_tag :email  %>
   </div>

   <div>
       <%= submit_tag "Submit Comment" %>
   </div>
<% end %>

app/views/landing/index.html.erb
<ul>
  <% @articles.each do |article| %>
    <li>
      <%= article.title %><br />
      <%= link_to 'Show Article', article_path(article) %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>